apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k423ywu6o-python
  janus-idp.io/tekton: k423ywu6o-python
  backstage.io/kubernetes-id: k423ywu6o-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k423ywu6o-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
